name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master", "r0.6.1" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/fastkafka-docusaurus-ghp@main
